apiVersion: v1
kind: Namespace
metadata:
  name: volbench
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volbenchtemp1
  namespace: volbench
spec:
  storageClassName: "fast"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volbench-runner
  namespace: volbench
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/sh"]
      args: ["-c", 'apt update; apt install -y fio git; git clone --single-branch --branch containerized http://github.com/rovandep/volbench.git; /volbench/k8s/volbench.sh; sleep 36000']
      volumeMounts:
        - mountPath: /mnt
          name: tmp1
      env:
      - name: FIO_files
        value: "/mnt/volbenchtest1 /mnt/volbenchtest2"
      - name: FIO_size
        value: "10MB"
      - name: FIO_ramptime
        value: "10"
      - name: FIO_runtime
        value: "60"
      - name: FIO_rwmixread
        value: "75"
      - name: FIO_fdatasync
        value: "0"
  volumes:
    - name: tmp1
      persistentVolumeClaim:
        claimName: volbenchtemp1
